# Generated by Django 6.0.1 on 2026-01-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolot', '0002_info_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='description',
            field=models.TextField(default=1, verbose_name='описания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=250, verbose_name='названия сайта'),
        ),
    ]
