# Generated by Django 6.0.1 on 2026-01-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolot', '0003_info_description_alter_info_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companyinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название компании')),
                ('about', models.TextField(verbose_name='Описание компании')),
                ('logo', models.ImageField(upload_to='', verbose_name='логотип компании')),
                ('address', models.CharField(max_length=250, verbose_name='адрес компании')),
                ('email', models.EmailField(max_length=254, verbose_name='контактный email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
        migrations.DeleteModel(
            name='info',
        ),
    ]
