# Generated by Django 6.0.1 on 2026-02-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolot', '0004_companyinfo_delete_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('profession', models.CharField(max_length=100, verbose_name='Профессия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Моя информация',
                'verbose_name_plural': 'Моя информация',
            },
        ),
        migrations.DeleteModel(
            name='Companyinfo',
        ),
    ]
